<?php

namespace Ls\ClientAssistant\Core\Router;

use Psr\Container\ContainerInterface;
use Psr\Http\Message\ResponseFactoryInterface;
use Slim\App;
use Slim\Factory\AppFactory;
use Slim\Interfaces\CallableResolverInterface;
use Slim\Interfaces\MiddlewareDispatcherInterface;
use Slim\Interfaces\RouteCollectorInterface;
use Slim\Interfaces\RouteResolverInterface;

class RouterAppFactoryAdapter extends AppFactory
{
    public static function createWithApiKey(string $apikey, string $coreUrl, string $appUrl, ?ResponseFactoryInterface $responseFactory = null, ?ContainerInterface $container = null, ?CallableResolverInterface $callableResolver = null, ?RouteCollectorInterface $routeCollector = null, ?RouteResolverInterface $routeResolver = null, ?MiddlewareDispatcherInterface $middlewareDispatcher = null): App
    {
        $GLOBALS['apikey'] = $apikey;
        $GLOBALS['coreUrl'] = $coreUrl;
        $GLOBALS['appUrl'] = str_ends_with($appUrl, '/') ? $appUrl : $appUrl . '/';

        return parent::create($responseFactory, $container, $callableResolver, $routeCollector, $routeResolver, $middlewareDispatcher); // TODO: Change the autogenerated stub
    }
}